### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by R3str** [R3str/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by Other-account** [comment]
### Fun fact
Ryu doesn't just ditch the shoes during a fight. He travels the world without any footwear on, at all. According to the UDON comics interpretation of the character, Ryu tells Sakura that walking around barefoot helps to build a person's character.

Various media have shown Ryu putting on shoes when needed, such as important functions like weddings, or traveling by air, but it doesn't appear like he'll break largely with tradition any time soon. That being said, Ryu did hint that he would be willing to rethink his no-shoe stance in Street Fighter X Tekken, so never say never.

### A dark secret
Street Fighter fans are aware of Ryu's precarious vulnerability to the Dark Hado, the same murderous energy that engulfed Akuma and led him down a path of evil and destruction. Ryu has attempted to banish the Dark Hado since it first openly manifested itself, with varying degrees of success.

Actually, the Satsui no Hado first took hold of Ryu during the original Street Fighter tournament. After climbing the ranks and battling Muay-Thai master Sagat, Ryu was nearly defeated. Without realizing it, Ryu was filled with the Dark Hado and lashed out at Sagat with his Dragon Punch, inflicting his opponent with his now-recognizable chest scar.

### The innermost fear
Psycho-powered criminal masterminds? Big deal! Dangerous Illuminati killers? No problem! Murderous demon-infused supervillains? Please! There's nothing Ryu can't handle ... except spiders, that is.

**Comment by R3str** [comment]
Wow!
